<?php

namespace Test\CsvImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersDataRepository extends EntityRepository
{
}
